---
title: "ema"
author: "andrew cardona"
date: "2025-06-24"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
library(tidyverse)
library(stringr)
library(dplyr)

############---- CLEAN UP CREW -----####################

# Define the renaming function
rename_survey_block <- function(df, question_text, prefix) {
  matching_cols <- colnames(df)[str_detect(str_to_lower(colnames(df)), str_to_lower(question_text))]
  
  if (length(matching_cols) == 0) {
    message(sprintf("No match found for: '%s'", question_text))
    return(df)
  }
  
  clean_names <- str_extract(matching_cols, "(?<=\\(choice=).+?(?=\\))")

  
  # Fallback for columns without (choice=...) format
  clean_names[is.na(clean_names)] <- paste0("item", seq_len(sum(is.na(clean_names))))
  
  new_names <- paste0(prefix, str_to_lower(str_replace_all(clean_names, "[^a-zA-Z0-9]", "_")))
  
  # Rename matched columns
  names(df)[match(matching_cols, names(df))] <- new_names
  
  return(df)
}
# renaming minutes 
rename_mins_columns <- function(df) {
  mins_map <- c(
    "Instagram" = "insta_mins",
    "X \\(formerly Twitter\\)" = "x_mins",
    "Facebook" = "fb_mins",
    "Snapchat" = "snap_mins",
    "TikTok" = "tiktok_mins",
    "YouTube" = "yt_mins",
    "Reddit" = "reddit_mins",
    "Tumblr" = "tumblr_mins",
    "Pinterest" = "pin_mins",
    "WhatsApp" = "wa_mins",
    "WeChat" = "wc_mins"
  )
  
  for (platform in names(mins_map)) {
    col_to_rename <- grep(paste0("how many minutes did you spend on ", platform),
                          colnames(df), ignore.case = TRUE, value = TRUE)
    if (length(col_to_rename) == 1) {
      colnames(df)[which(colnames(df) == col_to_rename)] <- mins_map[[platform]]
    }
  }
  
  return(df)
}
# renaming moods 
rename_mood_cols <- function(df) {
  # Create a named vector for the mapping
  mood_map <- c(
   "...5"   = "gen_mood",
   "...21"  = "insta_mood",
   "...67"  = "x_mood",
   "...111" = "fb_mood",
   "...159" = "snapchat_mood",
   "...199" = "tiktok_mood",
   "...244" = "yt_mood",
   "...293" = "reddit_mood",
   "...340" = "tumblr_mood",
   "...382" = "pin_mood",
   "...425" = "wa_mood",
   "...464" = "wc_mood"
 )
  
  # Find which of these columns exist in the df
 existing_cols <- intersect(names(mood_map), colnames(df))
  
  # Rename the matching columns
 colnames(df)[match(existing_cols, colnames(df))] <- mood_map[existing_cols]
  
 return(df)
}


# Folder containing CSVs
data_dir <- "/Users/andrewcardona/Desktop/CABLAB_CODE/EMA"  # << change this to where your EMA files are stored - recommend a seperate folder for EMA's :)
file_paths <- list.files(data_dir, pattern = "\\.csv$", full.names = TRUE)

# Process each file
renamed_dfs <- lapply(file_paths, function(path) {
  df <- read_csv(path)
  # Apply renaming for each block
  # ALL SoCiALS AGHH 
  df <- rename_survey_block(df, "Which of the following social media applications", "sm_")
  # insta baddie 
  df <- rename_survey_block(df, "why did you go on instagram", "insta_")
  df <- rename_survey_block(df, "instagram in the last hour", "insta_cont_")
  df <- rename_survey_block(df, "when you went on instagram, which of the following activities", "insta_act_")
  
  # X (twitter)
  df <- rename_survey_block(df, "why did you go on x", "x_")
  df <- rename_survey_block(df, "x in the last hour", "x_cont_")
  df <- rename_survey_block(df, "when you went on x, which of the following activities", "x_act_")
  
  # fb mom 
  df <- rename_survey_block(df, "facebook in the last hour", "fb_cont_")
  df <- rename_survey_block(df, "when you went on facebook, which of the following activities", "fb_act_")
  df <- rename_survey_block(df, "why did you go on facebook", "fb_")
  
  #snap demon 
  df <- rename_survey_block(df, "why did you go on snapchat", "snapchat_")
  df <- rename_survey_block(df, "snapchat in the last hour", "snapchat_content_")
  df <- rename_survey_block(df, "when you went on snapchat, which of the following activities", "snapchat_act_")

  # tik tok 
  df <- rename_survey_block(df, "why did you go on tiktok", "tiktok_")
  df <- rename_survey_block(df, "tiktok in the last hour", "tiktok_cont_")
  df <- rename_survey_block(df, "when you went on tiktok, which of the following activities", "tiktok_act_")
  
  # youtube 
  df <- rename_survey_block(df, "why did you go on youtube", "yt_")
  df <- rename_survey_block(df, "youtube in the last hour", "yt_cont_")
  df <- rename_survey_block(df, "when you went on youtube, which of the following activities", "yt_act_")
  
  # Reddit
  df <- rename_survey_block(df, "why did you go on reddit", "reddit_")
  df <- rename_survey_block(df, "reddit in the last hour", "reddit_cont_")
  df <- rename_survey_block(df, "when you went on reddit, which of the following activities", "reddit_act_")
  
  #Tumblr 
  df <- rename_survey_block(df, "why did you go on tumblr", "tumblr_")
  df <- rename_survey_block(df, "tumblr in the last hour", "tumblr_cont_")
  df <- rename_survey_block(df, "when you went on tumblr, which of the following activities", "tumblr_act_")
  
  #Pintrest
  df <- rename_survey_block(df, "why did you go on pinterest", "pin_")
  df <- rename_survey_block(df, "pinterest in the last hour", "pin_cont_")
  df <- rename_survey_block(df, "when you went on pinterest, which of the following activities", "pin_act_")
  
  #Whatsapp
  df <- rename_survey_block(df, "why did you go on whatsapp", "wa_")
  df <- rename_survey_block(df, "whatsapp in the last hour", "wa_cont_")
  df <- rename_survey_block(df, "when you went on whatsapp, which of the following activities", "wa_act_")
  
  #Wechat 
  df <- rename_survey_block(df, "why did you go on wechat", "wc_")
  df <- rename_survey_block(df, "wechat in the last hour", "wc_cont_")
  df <- rename_survey_block(df, "when you went on wechat, which of the following activities", "wc_act_")
  # renaming mins 
  df <- rename_mins_columns(df)
 # renaming moods 
  df <- rename_mood_cols(df)
   df[] <- lapply(df, function(col) {
    if (is.character(col) && all(na.omit(col) %in% c("Checked", "Unchecked"))) {
      return(ifelse(col == "Checked", 1, 0))
    } else {
      return(col)
    }
  })

  return(df)
})
```

```{r}
for (i in seq_along(renamed_dfs)) {
  # Extract EMA number
  ema_num <- str_extract(basename(file_paths[i]), "EMA\\d+")
  
  # Create new filename pls
  new_filename <- paste0("cleaned_", ema_num, ".csv")
  
  # Write the cleaned df back to the data_dir folder :)
  write_csv(renamed_dfs[[i]], file.path(data_dir, new_filename))
}

```
```{r}
# creating branching 


```
```{r}
colnames(df)
```



